AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Example basic lambda using `holy-lambda` micro library

Parameters:
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 512

Globals:
  Function:
    Timeout: !Ref Timeout
    MemorySize: !Ref MemorySize

Resources:
  ExampleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: provided.al2
      Handler: example.lambda.HttpAPIProxyGateway
      CodeUri: ./.holy-lambda/build/latest.zip
      Events:
        HelloEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ServerlessHttpApi
            Path: /{proxy+}
            Method: ANY

  ServerlessHttpApi:
    Type: AWS::Serverless::HttpApi
    DeletionPolicy: Retain
    Properties:
      StageName: Prod

Outputs:
  TestEndpoint:
    Description: Test endpoint
    Value:
      Fn::Sub: https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com
